### PR TITLE
Upgrade to beta 3

### PR DESCRIPTION
**Pull request by mineiwik**

### CODE REVIEW

**Comment by mineiwik** [comment]
It seems to work locally (even when using TLS) - but when Godot tries to make a connection using websocket to the remote server, the server instantaneously closes the connection - @siku2 Do you have any idea what is going on? (The HTTPS request to get the lobby id works fine)

**Comment by mineiwik** [comment]
Update:
The same happens locally when using `localhost` instead of the loop back IP (`127.0.0.1`) directly...

**Comment by mineiwik** [comment]
Update:
On Linux, everything works seamlessly...

**Comment by siku2** [comment]
The curious case of the disappearing comment :P

**Review by siku2 — APPROVED** [review]
Wow the new API seems kinda clumsy

**Pull request merged**
